### ISSUE TITLE
Please consider adding a list example

### ISSUE THREAD

**Issue by chrisinmtown** [meffie/libyaml-examples#1]
I'm just trying to learn libyaml myself, and it would be a big help if the fruit and parse examples showed how to parse, store and traverse a boolean value and an internal list. Maybe add properties "isRipe" and "varieties"?  :) please consider it.

**Comment by meffie** [comment]
Hi, Sure, but I'm not quite sure what you are looking for. Can you provide an example yaml file?

**Comment by chrisinmtown** [comment]
good day and thanks for the reply. I was thinking something like this, where a list for an item can have a varying number of elements:
```
    fruit:
    - name: apple
      color: red
      count: 12
      varieties:
        - name: granny smith
          seeds: True
        - name: empire
          seeds: True
    - name: orange
      color: orange
      count: 3
      varieties:
        - name: navel
          seeds: False
```
